//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Mon Nov 25 23:06:56 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_putA                       O     1 const
// RDY_putB                       O     1 const
// RDY_putS                       O     1 const
// getA                           O    16 reg
// RDY_getA                       O     1 const
// getB                           O    16 reg
// RDY_getB                       O     1 const
// getC                           O    32 reg
// RDY_getC                       O     1 const
// getS                           O     1
// RDY_getS                       O     1 const
// validAB                        O     1 reg
// RDY_validAB                    O     1 const
// RDY_reset_mod                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// putA_in_a                      I    16
// putB_in_b                      I    16
// putS_in_c                      I     1
// EN_putA                        I     1
// EN_putB                        I     1
// EN_putS                        I     1
// EN_reset_mod                   I     1
//
// Combinational paths from inputs to outputs:
//   (putS_in_c, EN_putS) -> getS
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mk_pe(CLK,
	     RST_N,

	     putA_in_a,
	     EN_putA,
	     RDY_putA,

	     putB_in_b,
	     EN_putB,
	     RDY_putB,

	     putS_in_c,
	     EN_putS,
	     RDY_putS,

	     getA,
	     RDY_getA,

	     getB,
	     RDY_getB,

	     getC,
	     RDY_getC,

	     getS,
	     RDY_getS,

	     validAB,
	     RDY_validAB,

	     EN_reset_mod,
	     RDY_reset_mod);
  input  CLK;
  input  RST_N;

  // action method putA
  input  [15 : 0] putA_in_a;
  input  EN_putA;
  output RDY_putA;

  // action method putB
  input  [15 : 0] putB_in_b;
  input  EN_putB;
  output RDY_putB;

  // action method putS
  input  putS_in_c;
  input  EN_putS;
  output RDY_putS;

  // value method getA
  output [15 : 0] getA;
  output RDY_getA;

  // value method getB
  output [15 : 0] getB;
  output RDY_getB;

  // value method getC
  output [31 : 0] getC;
  output RDY_getC;

  // value method getS
  output getS;
  output RDY_getS;

  // value method validAB
  output validAB;
  output RDY_validAB;

  // action method reset_mod
  input  EN_reset_mod;
  output RDY_reset_mod;

  // signals for module outputs
  wire [31 : 0] getC;
  wire [15 : 0] getA, getB;
  wire RDY_getA,
       RDY_getB,
       RDY_getC,
       RDY_getS,
       RDY_putA,
       RDY_putB,
       RDY_putS,
       RDY_reset_mod,
       RDY_validAB,
       getS,
       validAB;

  // register rg_out_a
  reg [15 : 0] rg_out_a;
  wire [15 : 0] rg_out_a$D_IN;
  wire rg_out_a$EN;

  // register rg_out_b
  reg [15 : 0] rg_out_b;
  wire [15 : 0] rg_out_b$D_IN;
  wire rg_out_b$EN;

  // register rg_out_c
  reg [31 : 0] rg_out_c;
  wire [31 : 0] rg_out_c$D_IN;
  wire rg_out_c$EN;

  // register valid_a_b
  reg valid_a_b;
  wire valid_a_b$D_IN, valid_a_b$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_propagate;

  // inputs to muxes for submodule ports
  wire [31 : 0] MUX_rg_out_c$write_1__VAL_1;
  wire MUX_rg_out_c$write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h58656;
  reg [63 : 0] v__h58740;
  reg [63 : 0] v__h58824;
  // synopsys translate_on

  // remaining internal signals
  wire [32 : 0] IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q10,
		IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q8,
		IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q9,
		IF_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELS_ETC__q1,
		IF_x5054_AND_y5055_THEN_2_ELSE_0__q11,
		IF_x8214_OR_y8215_THEN_3_ELSE_1__q12;
  wire [31 : 0] IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d42,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94,
		IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC__q2,
		_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106,
		_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112,
		b__h11129,
		carry__h11212,
		carry__h11277,
		carry__h11342,
		carry__h11407,
		carry__h11472,
		carry__h11537,
		cin__h11130,
		partial_product__h11125,
		partial_product__h11209,
		partial_product__h11274,
		partial_product__h11339,
		partial_product__h11404,
		partial_product__h11469,
		partial_product__h11534,
		product__h11211,
		product__h11276,
		product__h11341,
		product__h11406,
		product__h11471,
		product__h11536,
		product__h11601,
		x1233_OR_y1234__q7,
		x1298_OR_y1299__q6,
		x1363_OR_y1364__q5,
		x1428_OR_y1429__q4,
		x1493_OR_y1494__q3,
		x__h11150,
		x__h11233,
		x__h11235,
		x__h11298,
		x__h11300,
		x__h11363,
		x__h11365,
		x__h11428,
		x__h11430,
		x__h11493,
		x__h11495,
		x__h11679,
		x__h11695,
		x__h11711,
		x__h11727,
		x__h11743,
		x__h11776,
		x__h11778,
		y__h11234,
		y__h11236,
		y__h11299,
		y__h11301,
		y__h11364,
		y__h11366,
		y__h11429,
		y__h11431,
		y__h11494,
		y__h11496,
		y__h11777,
		y__h11779;
  wire [30 : 0] IF_IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_i_ETC___d551,
		IF_NOT_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr__ETC___d549;
  wire [22 : 0] IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC__q13,
		IF_mantissa_b10_BIT_0_THEN_1_ELSE_0__q14,
		mantissa_a__h706,
		mantissa_b___1__h52025,
		mantissa_b__h710,
		sum_mantissa___1__h58472,
		sum_mantissa___2__h58442,
		sum_mantissa__h711,
		sum_mantissa__h714;
  wire [21 : 0] IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d535;
  wire [17 : 0] IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d526;
  wire [15 : 0] IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17,
		IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21;
  wire [12 : 0] _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d267;
  wire [10 : 0] _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d266;
  wire [8 : 0] _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d265;
  wire [7 : 0] IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d304,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404,
	       _theResult_____1_fst__h19360,
	       _theResult_____1_fst__h19414,
	       _theResult_____1_fst_exponent__h58475,
	       _theResult_____2_fst_exponent__h58478,
	       _theResult_____2_fst_exponent__h58487,
	       exponent_a__h705,
	       exponent_difference__h707,
	       fraction___1__h35349,
	       fraction__h19358,
	       fraction__h35303;
  wire [6 : 0] IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d347,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d264,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d343;
  wire [5 : 0] IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d460,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d298;
  wire [4 : 0] _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d263,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d342;
  wire [3 : 0] IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d459,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d297;
  wire [2 : 0] _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d262,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d341;
  wire IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d509,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d511,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d513,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d515,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d517,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d519,
       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d520,
       IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d469,
       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d246,
       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247,
       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d248,
       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273,
       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316,
       a_sign__h725,
       wr_valid_a_whas_AND_wr_valid_a_wget_AND_wr_val_ETC___d14,
       x__h12515,
       x__h12668,
       x__h12714,
       x__h12820,
       x__h12866,
       x__h12972,
       x__h13018,
       x__h13124,
       x__h13170,
       x__h13276,
       x__h13322,
       x__h13428,
       x__h13474,
       x__h13580,
       x__h13626,
       x__h13732,
       x__h13778,
       x__h13884,
       x__h13930,
       x__h14036,
       x__h14082,
       x__h14188,
       x__h14234,
       x__h14340,
       x__h14386,
       x__h14492,
       x__h14538,
       x__h14644,
       x__h14690,
       x__h14796,
       x__h14842,
       x__h14948,
       x__h14994,
       x__h15100,
       x__h15146,
       x__h15252,
       x__h15298,
       x__h15404,
       x__h15450,
       x__h15556,
       x__h15602,
       x__h15754,
       x__h21148,
       x__h21298,
       x__h21448,
       x__h21598,
       x__h21748,
       x__h21898,
       x__h28214,
       x__h28216,
       x__h28360,
       x__h28362,
       x__h28511,
       x__h28513,
       x__h28556,
       x__h28661,
       x__h28663,
       x__h28706,
       x__h28811,
       x__h28813,
       x__h28856,
       x__h28961,
       x__h28963,
       x__h29006,
       x__h29111,
       x__h29113,
       x__h29156,
       x__h29263,
       x__h29306,
       x__h3255,
       x__h3406,
       x__h3451,
       x__h3556,
       x__h3601,
       x__h3706,
       x__h37063,
       x__h37213,
       x__h37363,
       x__h3751,
       x__h37513,
       x__h37663,
       x__h37813,
       x__h3856,
       x__h3901,
       x__h4006,
       x__h4051,
       x__h4201,
       x__h45054,
       x__h45394,
       x__h45544,
       x__h45694,
       x__h45844,
       x__h45994,
       x__h56812,
       x__h57080,
       x__h57171,
       x__h57352,
       x__h57443,
       x__h57623,
       x__h57714,
       x__h57894,
       x__h57985,
       x__h58165,
       x__h58256,
       y__h12516,
       y__h12562,
       y__h12669,
       y__h12715,
       y__h12821,
       y__h12867,
       y__h12973,
       y__h13019,
       y__h13125,
       y__h13171,
       y__h13277,
       y__h13323,
       y__h13429,
       y__h13475,
       y__h13581,
       y__h13627,
       y__h13733,
       y__h13779,
       y__h13885,
       y__h13931,
       y__h14037,
       y__h14083,
       y__h14189,
       y__h14235,
       y__h14341,
       y__h14387,
       y__h14493,
       y__h14539,
       y__h14645,
       y__h14691,
       y__h14797,
       y__h14843,
       y__h14949,
       y__h14995,
       y__h15101,
       y__h15147,
       y__h15253,
       y__h15299,
       y__h15405,
       y__h15451,
       y__h15557,
       y__h15603,
       y__h15755,
       y__h28215,
       y__h28361,
       y__h28406,
       y__h28512,
       y__h28557,
       y__h28662,
       y__h28707,
       y__h28812,
       y__h28857,
       y__h28962,
       y__h29007,
       y__h29112,
       y__h29157,
       y__h29307,
       y__h3256,
       y__h3301,
       y__h3407,
       y__h3452,
       y__h3557,
       y__h3602,
       y__h36913,
       y__h37064,
       y__h3707,
       y__h37214,
       y__h37364,
       y__h37514,
       y__h3752,
       y__h37664,
       y__h37814,
       y__h3857,
       y__h3902,
       y__h4007,
       y__h4052,
       y__h4202,
       y__h45055,
       y__h45244,
       y__h45395,
       y__h45545,
       y__h45695,
       y__h45845,
       y__h57081,
       y__h57172,
       y__h57174,
       y__h57353,
       y__h57444,
       y__h57446,
       y__h57624,
       y__h57715,
       y__h57717,
       y__h57895,
       y__h57986,
       y__h57988,
       y__h58166,
       y__h58257,
       y__h58259;

  // action method putA
  assign RDY_putA = 1'd1 ;

  // action method putB
  assign RDY_putB = 1'd1 ;

  // action method putS
  assign RDY_putS = 1'd1 ;

  // value method getA
  assign getA = rg_out_a ;
  assign RDY_getA = 1'd1 ;

  // value method getB
  assign getB = rg_out_b ;
  assign RDY_getB = 1'd1 ;

  // value method getC
  assign getC = rg_out_c ;
  assign RDY_getC = 1'd1 ;

  // value method getS
  assign getS = EN_putS && putS_in_c ;
  assign RDY_getS = 1'd1 ;

  // value method validAB
  assign validAB = valid_a_b ;
  assign RDY_validAB = 1'd1 ;

  // action method reset_mod
  assign RDY_reset_mod = 1'd1 ;

  // rule RL_propagate
  assign WILL_FIRE_RL_propagate = EN_putA && EN_putB && !EN_reset_mod ;

  // inputs to muxes for submodule ports
  assign MUX_rg_out_c$write_1__SEL_1 =
	     !EN_reset_mod &&
	     wr_valid_a_whas_AND_wr_valid_a_wget_AND_wr_val_ETC___d14 ;
  assign MUX_rg_out_c$write_1__VAL_1 =
	     { (a_sign__h725 == rg_out_c[31]) ?
		 a_sign__h725 :
		 IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d469,
	       IF_IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_i_ETC___d551 } ;

  // register rg_out_a
  assign rg_out_a$D_IN =
	     WILL_FIRE_RL_propagate ?
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17 :
	       16'd0 ;
  assign rg_out_a$EN = WILL_FIRE_RL_propagate || EN_reset_mod ;

  // register rg_out_b
  assign rg_out_b$D_IN =
	     WILL_FIRE_RL_propagate ?
	       IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21 :
	       16'd0 ;
  assign rg_out_b$EN = WILL_FIRE_RL_propagate || EN_reset_mod ;

  // register rg_out_c
  assign rg_out_c$D_IN =
	     MUX_rg_out_c$write_1__SEL_1 ?
	       MUX_rg_out_c$write_1__VAL_1 :
	       32'd0 ;
  assign rg_out_c$EN =
	     !EN_reset_mod &&
	     wr_valid_a_whas_AND_wr_valid_a_wget_AND_wr_val_ETC___d14 ||
	     EN_reset_mod ;

  // register valid_a_b
  assign valid_a_b$D_IN =
	     wr_valid_a_whas_AND_wr_valid_a_wget_AND_wr_val_ETC___d14 ;
  assign valid_a_b$EN = !EN_reset_mod ;

  // remaining internal signals
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d304 =
	     (_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247 &&
	      { _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d248,
		_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d267 } !=
	      14'b01000000000000) ?
	       fraction___1__h35349 :
	       fraction__h35303 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d347 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316 ?
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d343 :
	       { y__h45845,
		 y__h45695,
		 y__h45545,
		 y__h45395,
		 y__h45244,
		 x__h45054,
		 y__h45055 } ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d246 ?
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d304 :
	       _theResult_____1_fst__h19360 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404 =
	     (_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d246 ||
	      _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d248 &&
	      _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d267 !=
	      13'b0100000000000 &&
	      _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316) ?
	       8'd129 :
	       8'd128 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d509 =
	     x__h58165 ^ y__h58166 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d511 =
	     x__h57894 ^ y__h57895 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d513 =
	     x__h57623 ^ y__h57624 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d515 =
	     x__h57352 ^ y__h57353 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d517 =
	     x__h57080 ^ y__h57081 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d519 =
	     x__h56812 ^
	     IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC__q13[16] ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d520 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[0] ^
	     mantissa_b__h710[16] ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d526 =
	     { IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d519,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d520,
	       mantissa_b__h710[15:1],
	       IF_mantissa_b10_BIT_0_THEN_1_ELSE_0__q14[0] } ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q10 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 ?
	       33'd2 :
	       33'd0 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q8 =
	     (_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[1] &
	      _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[0]) ?
	       33'd4 :
	       33'd0 ;
  assign IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q9 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247 ?
	       33'd2 :
	       33'd0 ;
  assign IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d469 =
	     (mantissa_a__h706 <= mantissa_b__h710) ?
	       rg_out_c[31] :
	       a_sign__h725 ;
  assign IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d535 =
	     (sum_mantissa__h711 == 23'd1) ?
	       { IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d509,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d511,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d513,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d515,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d517,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d519,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d520,
		 mantissa_b__h710[15:1] } :
	       { IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d511,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d513,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d515,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d517,
		 IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d526 } ;
  assign IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC__q13 =
	     (IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[0] &
	      mantissa_b__h710[16]) ?
	       23'd65536 :
	       23'd0 ;
  assign IF_IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_i_ETC___d551 =
	     IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d535[0] ?
	       IF_NOT_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr__ETC___d549 :
	       { _theResult_____2_fst_exponent__h58487, sum_mantissa__h714 } ;
  assign IF_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELS_ETC__q1 =
	     (IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[7] &
	      IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[7]) ?
	       33'd2 :
	       33'd0 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d42 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[0] ?
	       product__h11601 :
	       32'd0 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[1] ?
	       carry__h11537 :
	       32'd0 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[1] ?
	       product__h11536 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d42 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[2] ?
	       carry__h11472 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[2] ?
	       product__h11471 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[3] ?
	       carry__h11407 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[3] ?
	       product__h11406 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[4] ?
	       carry__h11342 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[4] ?
	       product__h11341 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[5] ?
	       carry__h11277 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[5] ?
	       product__h11276 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83 ;
  assign IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC__q2 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d42 &
	     partial_product__h11534 ;
  assign IF_NOT_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr__ETC___d549 =
	     sum_mantissa___2__h58442[22] ?
	       { _theResult_____1_fst_exponent__h58475,
		 sum_mantissa___1__h58472 } :
	       { _theResult_____2_fst_exponent__h58487,
		 sum_mantissa___2__h58442 } ;
  assign IF_mantissa_b10_BIT_0_THEN_1_ELSE_0__q14 =
	     mantissa_b__h710[0] ? 23'd1 : 23'd0 ;
  assign IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d459 =
	     { y__h28707 ^ x__h28706,
	       y__h28557 ^ x__h28556,
	       y__h28406 ^ IF_x8214_OR_y8215_THEN_3_ELSE_1__q12[1],
	       ~y__h28215 } ;
  assign IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d460 =
	     { y__h29007 ^ x__h29006,
	       y__h28857 ^ x__h28856,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d459 } ;
  assign IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17 =
	     EN_putA ? putA_in_a : 16'd0 ;
  assign IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21 =
	     EN_putB ? putB_in_b : 16'd0 ;
  assign IF_x5054_AND_y5055_THEN_2_ELSE_0__q11 =
	     (x__h45054 & y__h45055) ? 33'd2 : 33'd0 ;
  assign IF_x8214_OR_y8215_THEN_3_ELSE_1__q12 =
	     (x__h28214 | y__h28215) ? 33'd3 : 33'd1 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106 =
	     x__h11150 ^ cin__h11130 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112 =
	     x__h11776 | y__h11777 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d246 =
	     y__h15755 ^ x__h15754 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247 =
	     y__h14387 ^ x__h14386 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d248 =
	     y__h14235 ^ x__h14234 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d262 =
	     { y__h12562 ^
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q8[2],
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[1] ^
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[0],
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[0] } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d263 =
	     { y__h12867 ^ x__h12866,
	       y__h12715 ^ x__h12714,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d262 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d264 =
	     { y__h13171 ^ x__h13170,
	       y__h13019 ^ x__h13018,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d263 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d265 =
	     { y__h13475 ^ x__h13474,
	       y__h13323 ^ x__h13322,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d264 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d266 =
	     { y__h13779 ^ x__h13778,
	       y__h13627 ^ x__h13626,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d265 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d267 =
	     { y__h14083 ^ x__h14082,
	       y__h13931 ^ x__h13930,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d266 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 =
	     y__h14539 ^ x__h14538 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d297 =
	     { y__h37214 ^ x__h37213,
	       y__h37064 ^ x__h37063,
	       y__h36913 ^
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q10[1],
	       ~_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d298 =
	     { y__h37514 ^ x__h37513,
	       y__h37364 ^ x__h37363,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d297 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316 =
	     y__h37664 ^ x__h21898 ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d341 =
	     { y__h45395 ^ x__h45394,
	       y__h45244 ^ IF_x5054_AND_y5055_THEN_2_ELSE_0__q11[1],
	       x__h45054 ^ y__h45055 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d342 =
	     { y__h45695 ^ x__h45694,
	       y__h45545 ^ x__h45544,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d341 } ;
  assign _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d343 =
	     { _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316 ^
	       x__h45994,
	       y__h45845 ^ x__h45844,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d342 } ;
  assign _theResult_____1_fst__h19360 =
	     (_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d248 &&
	      _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d267 !=
	      13'b0100000000000) ?
	       _theResult_____1_fst__h19414 :
	       fraction__h19358 ;
  assign _theResult_____1_fst__h19414 =
	     { x__h45994 &
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d316,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d347 } ;
  assign _theResult_____1_fst_exponent__h58475 =
	     _theResult_____2_fst_exponent__h58487 + 8'd1 ;
  assign _theResult_____2_fst_exponent__h58478 = exponent_a__h705 + 8'd1 ;
  assign _theResult_____2_fst_exponent__h58487 =
	     (sum_mantissa__h711 == 23'd1) ?
	       _theResult_____2_fst_exponent__h58478 :
	       exponent_a__h705 ;
  assign a_sign__h725 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[15] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[15] ;
  assign b__h11129 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[6] ?
	       carry__h11212 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90 ;
  assign carry__h11212 = { x1233_OR_y1234__q7[30:0], 1'd0 } ;
  assign carry__h11277 = { x1298_OR_y1299__q6[30:0], 1'd0 } ;
  assign carry__h11342 = { x1363_OR_y1364__q5[30:0], 1'd0 } ;
  assign carry__h11407 = { x1428_OR_y1429__q4[30:0], 1'd0 } ;
  assign carry__h11472 = { x1493_OR_y1494__q3[30:0], 1'd0 } ;
  assign carry__h11537 =
	     { IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC__q2[30:0],
	       1'd0 } ;
  assign cin__h11130 =
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[6] ?
	       product__h11211 :
	       IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94 ;
  assign exponent_a__h705 =
	     { y__h29307 ^ x__h29306,
	       y__h29157 ^ x__h29156,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0_ETC___d460 } ;
  assign exponent_difference__h707 = exponent_a__h705 - rg_out_c[30:23] ;
  assign fraction___1__h35349 =
	     { y__h37814 ^ x__h37813,
	       y__h37664 ^ x__h37663,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d298 } ;
  assign fraction__h19358 =
	     { y__h37664,
	       y__h37514,
	       y__h37364,
	       y__h37214,
	       y__h37064,
	       y__h36913,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247 } ;
  assign fraction__h35303 =
	     { y__h37814,
	       y__h37664,
	       y__h37514,
	       y__h37364,
	       y__h37214,
	       y__h37064,
	       y__h36913,
	       _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 } ;
  assign mantissa_a__h706 =
	     { IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[6:0],
	       16'b0 } ;
  assign mantissa_b___1__h52025 =
	     rg_out_c[22:0] >> exponent_difference__h707 ;
  assign mantissa_b__h710 =
	     (exponent_difference__h707 == 8'd0) ?
	       rg_out_c[22:0] :
	       mantissa_b___1__h52025 ;
  assign partial_product__h11125 =
	     { 18'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       7'd0 } ;
  assign partial_product__h11209 =
	     { 19'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       6'd0 } ;
  assign partial_product__h11274 =
	     { 20'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       5'd0 } ;
  assign partial_product__h11339 =
	     { 21'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       4'd0 } ;
  assign partial_product__h11404 =
	     { 22'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       3'd0 } ;
  assign partial_product__h11469 =
	     { 23'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       2'd0 } ;
  assign partial_product__h11534 =
	     { 24'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0],
	       1'd0 } ;
  assign product__h11211 =
	     x__h11743 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94 ;
  assign product__h11276 =
	     x__h11727 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83 ;
  assign product__h11341 =
	     x__h11711 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72 ;
  assign product__h11406 =
	     x__h11695 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61 ;
  assign product__h11471 =
	     x__h11679 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50 ;
  assign product__h11536 =
	     partial_product__h11534 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d42 ;
  assign product__h11601 =
	     { 25'd1,
	       IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[6:0] } ;
  assign sum_mantissa___1__h58472 = { 1'd0, sum_mantissa___2__h58442[22:1] } ;
  assign sum_mantissa___2__h58442 = sum_mantissa__h714 + 23'd1 ;
  assign sum_mantissa__h711 =
	     { IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d509,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d511,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d513,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d515,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d517,
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d526 } ;
  assign sum_mantissa__h714 =
	     { sum_mantissa__h711 != 23'd1 &&
	       IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d509,
	       IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC___d535 } ;
  assign wr_valid_a_whas_AND_wr_valid_a_wget_AND_wr_val_ETC___d14 =
	     EN_putA && EN_putB ;
  assign x1233_OR_y1234__q7 = x__h11233 | y__h11234 ;
  assign x1298_OR_y1299__q6 = x__h11298 | y__h11299 ;
  assign x1363_OR_y1364__q5 = x__h11363 | y__h11364 ;
  assign x1428_OR_y1429__q4 = x__h11428 | y__h11429 ;
  assign x1493_OR_y1494__q3 = x__h11493 | y__h11494 ;
  assign x__h11150 = partial_product__h11125 ^ b__h11129 ;
  assign x__h11233 = x__h11235 | y__h11236 ;
  assign x__h11235 =
	     partial_product__h11209 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90 ;
  assign x__h11298 = x__h11300 | y__h11301 ;
  assign x__h11300 =
	     partial_product__h11274 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79 ;
  assign x__h11363 = x__h11365 | y__h11366 ;
  assign x__h11365 =
	     partial_product__h11339 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68 ;
  assign x__h11428 = x__h11430 | y__h11431 ;
  assign x__h11430 =
	     partial_product__h11404 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57 ;
  assign x__h11493 = x__h11495 | y__h11496 ;
  assign x__h11495 =
	     partial_product__h11469 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47 ;
  assign x__h11679 =
	     partial_product__h11469 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47 ;
  assign x__h11695 =
	     partial_product__h11404 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57 ;
  assign x__h11711 =
	     partial_product__h11339 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68 ;
  assign x__h11727 =
	     partial_product__h11274 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79 ;
  assign x__h11743 =
	     partial_product__h11209 ^
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90 ;
  assign x__h11776 = x__h11778 | y__h11779 ;
  assign x__h11778 = partial_product__h11125 & b__h11129 ;
  assign x__h12515 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[2] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[1] ;
  assign x__h12668 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[3] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[2] ;
  assign x__h12714 = x__h12515 | y__h12516 ;
  assign x__h12820 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[4] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[3] ;
  assign x__h12866 = x__h12668 | y__h12669 ;
  assign x__h12972 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[5] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[4] ;
  assign x__h13018 = x__h12820 | y__h12821 ;
  assign x__h13124 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[6] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[5] ;
  assign x__h13170 = x__h12972 | y__h12973 ;
  assign x__h13276 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[7] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[6] ;
  assign x__h13322 = x__h13124 | y__h13125 ;
  assign x__h13428 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[8] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[7] ;
  assign x__h13474 = x__h13276 | y__h13277 ;
  assign x__h13580 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[9] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[8] ;
  assign x__h13626 = x__h13428 | y__h13429 ;
  assign x__h13732 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[10] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[9] ;
  assign x__h13778 = x__h13580 | y__h13581 ;
  assign x__h13884 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[11] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[10] ;
  assign x__h13930 = x__h13732 | y__h13733 ;
  assign x__h14036 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[12] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[11] ;
  assign x__h14082 = x__h13884 | y__h13885 ;
  assign x__h14188 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[13] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[12] ;
  assign x__h14234 = x__h14036 | y__h14037 ;
  assign x__h14340 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[14] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[13] ;
  assign x__h14386 = x__h14188 | y__h14189 ;
  assign x__h14492 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[15] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[14] ;
  assign x__h14538 = x__h14340 | y__h14341 ;
  assign x__h14644 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[16] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[15] ;
  assign x__h14690 = x__h14492 | y__h14493 ;
  assign x__h14796 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[17] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[16] ;
  assign x__h14842 = x__h14644 | y__h14645 ;
  assign x__h14948 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[18] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[17] ;
  assign x__h14994 = x__h14796 | y__h14797 ;
  assign x__h15100 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[19] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[18] ;
  assign x__h15146 = x__h14948 | y__h14949 ;
  assign x__h15252 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[20] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[19] ;
  assign x__h15298 = x__h15100 | y__h15101 ;
  assign x__h15404 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[21] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[20] ;
  assign x__h15450 = x__h15252 | y__h15253 ;
  assign x__h15556 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[22] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[21] ;
  assign x__h15602 = x__h15404 | y__h15405 ;
  assign x__h15754 = x__h15556 | y__h15557 ;
  assign x__h21148 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q9[1] &
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 ;
  assign x__h21298 = x__h21148 & y__h36913 ;
  assign x__h21448 = x__h21298 & y__h37064 ;
  assign x__h21598 = x__h21448 & y__h37214 ;
  assign x__h21748 = x__h21598 & y__h37364 ;
  assign x__h21898 = x__h21748 & y__h37514 ;
  assign x__h28214 =
	     x__h28216 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[0] ;
  assign x__h28216 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[7] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[7] ;
  assign x__h28360 =
	     x__h28362 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[1] ;
  assign x__h28362 =
	     y__h3301 ^
	     IF_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELS_ETC__q1[1] ;
  assign x__h28511 =
	     x__h28513 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[2] ;
  assign x__h28513 = y__h3452 ^ x__h3451 ;
  assign x__h28556 = x__h28360 | y__h28361 ;
  assign x__h28661 =
	     x__h28663 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[3] ;
  assign x__h28663 = y__h3602 ^ x__h3601 ;
  assign x__h28706 = x__h28511 | y__h28512 ;
  assign x__h28811 =
	     x__h28813 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[4] ;
  assign x__h28813 = y__h3752 ^ x__h3751 ;
  assign x__h28856 = x__h28661 | y__h28662 ;
  assign x__h28961 =
	     x__h28963 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[5] ;
  assign x__h28963 = y__h3902 ^ x__h3901 ;
  assign x__h29006 = x__h28811 | y__h28812 ;
  assign x__h29111 =
	     x__h29113 &
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[6] ;
  assign x__h29113 = y__h4052 ^ x__h4051 ;
  assign x__h29156 = x__h28961 | y__h28962 ;
  assign x__h29263 = y__h4202 ^ x__h4201 ;
  assign x__h29306 = x__h29111 | y__h29112 ;
  assign x__h3255 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[8] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[8] ;
  assign x__h3406 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[9] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[9] ;
  assign x__h3451 = x__h3255 | y__h3256 ;
  assign x__h3556 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[10] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[10] ;
  assign x__h3601 = x__h3406 | y__h3407 ;
  assign x__h3706 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[11] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[11] ;
  assign x__h37063 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q10[1] &
	     y__h36913 ;
  assign x__h37213 = x__h37063 & y__h37064 ;
  assign x__h37363 = x__h37213 & y__h37214 ;
  assign x__h3751 = x__h3556 | y__h3557 ;
  assign x__h37513 = x__h37363 & y__h37364 ;
  assign x__h37663 = x__h37513 & y__h37514 ;
  assign x__h37813 = x__h37663 & y__h37664 ;
  assign x__h3856 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[12] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[12] ;
  assign x__h3901 = x__h3706 | y__h3707 ;
  assign x__h4006 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[13] &
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[13] ;
  assign x__h4051 = x__h3856 | y__h3857 ;
  assign x__h4201 = x__h4006 | y__h4007 ;
  assign x__h45054 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d273 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q9[1] ;
  assign x__h45394 = IF_x5054_AND_y5055_THEN_2_ELSE_0__q11[1] & y__h45244 ;
  assign x__h45544 = x__h45394 & y__h45395 ;
  assign x__h45694 = x__h45544 & y__h45545 ;
  assign x__h45844 = x__h45694 & y__h45695 ;
  assign x__h45994 = x__h45844 & y__h45845 ;
  assign x__h56812 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[1] ^
	     mantissa_b__h710[17] ;
  assign x__h57080 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[2] ^
	     mantissa_b__h710[18] ;
  assign x__h57171 =
	     IF_IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_ETC__q13[16] &
	     y__h57174 ;
  assign x__h57352 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[3] ^
	     mantissa_b__h710[19] ;
  assign x__h57443 = y__h57081 & y__h57446 ;
  assign x__h57623 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[4] ^
	     mantissa_b__h710[20] ;
  assign x__h57714 = y__h57353 & y__h57717 ;
  assign x__h57894 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[5] ^
	     mantissa_b__h710[21] ;
  assign x__h57985 = y__h57624 & y__h57988 ;
  assign x__h58165 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[6] ^
	     mantissa_b__h710[22] ;
  assign x__h58256 = y__h57895 & y__h58259 ;
  assign y__h11234 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94 &
	     partial_product__h11209 ;
  assign y__h11236 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d90 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d94 ;
  assign y__h11299 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83 &
	     partial_product__h11274 ;
  assign y__h11301 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d79 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d83 ;
  assign y__h11364 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72 &
	     partial_product__h11339 ;
  assign y__h11366 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d68 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d72 ;
  assign y__h11429 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61 &
	     partial_product__h11404 ;
  assign y__h11431 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d57 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d61 ;
  assign y__h11494 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50 &
	     partial_product__h11469 ;
  assign y__h11496 =
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d47 &
	     IF_IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELS_ETC___d50 ;
  assign y__h11777 = cin__h11130 & partial_product__h11125 ;
  assign y__h11779 = b__h11129 & cin__h11130 ;
  assign y__h12516 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC__q8[2] &
	     y__h12562 ;
  assign y__h12562 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[2] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[1] ;
  assign y__h12669 = x__h12714 & y__h12715 ;
  assign y__h12715 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[3] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[2] ;
  assign y__h12821 = x__h12866 & y__h12867 ;
  assign y__h12867 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[4] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[3] ;
  assign y__h12973 = x__h13018 & y__h13019 ;
  assign y__h13019 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[5] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[4] ;
  assign y__h13125 = x__h13170 & y__h13171 ;
  assign y__h13171 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[6] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[5] ;
  assign y__h13277 = x__h13322 & y__h13323 ;
  assign y__h13323 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[7] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[6] ;
  assign y__h13429 = x__h13474 & y__h13475 ;
  assign y__h13475 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[8] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[7] ;
  assign y__h13581 = x__h13626 & y__h13627 ;
  assign y__h13627 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[9] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[8] ;
  assign y__h13733 = x__h13778 & y__h13779 ;
  assign y__h13779 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[10] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[9] ;
  assign y__h13885 = x__h13930 & y__h13931 ;
  assign y__h13931 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[11] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[10] ;
  assign y__h14037 = x__h14082 & y__h14083 ;
  assign y__h14083 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[12] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[11] ;
  assign y__h14189 = x__h14234 & y__h14235 ;
  assign y__h14235 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[13] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[12] ;
  assign y__h14341 = x__h14386 & y__h14387 ;
  assign y__h14387 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[14] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[13] ;
  assign y__h14493 = x__h14538 & y__h14539 ;
  assign y__h14539 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[15] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[14] ;
  assign y__h14645 = x__h14690 & y__h14691 ;
  assign y__h14691 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[16] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[15] ;
  assign y__h14797 = x__h14842 & y__h14843 ;
  assign y__h14843 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[17] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[16] ;
  assign y__h14949 = x__h14994 & y__h14995 ;
  assign y__h14995 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[18] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[17] ;
  assign y__h15101 = x__h15146 & y__h15147 ;
  assign y__h15147 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[19] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[18] ;
  assign y__h15253 = x__h15298 & y__h15299 ;
  assign y__h15299 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[20] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[19] ;
  assign y__h15405 = x__h15450 & y__h15451 ;
  assign y__h15451 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[21] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[20] ;
  assign y__h15557 = x__h15602 & y__h15603 ;
  assign y__h15603 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[22] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[21] ;
  assign y__h15755 =
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d106[23] ^
	     _1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d112[22] ;
  assign y__h28215 =
	     x__h28216 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[0] ;
  assign y__h28361 = IF_x8214_OR_y8215_THEN_3_ELSE_1__q12[1] & y__h28406 ;
  assign y__h28406 =
	     x__h28362 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[1] ;
  assign y__h28512 = x__h28556 & y__h28557 ;
  assign y__h28557 =
	     x__h28513 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[2] ;
  assign y__h28662 = x__h28706 & y__h28707 ;
  assign y__h28707 =
	     x__h28663 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[3] ;
  assign y__h28812 = x__h28856 & y__h28857 ;
  assign y__h28857 =
	     x__h28813 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[4] ;
  assign y__h28962 = x__h29006 & y__h29007 ;
  assign y__h29007 =
	     x__h28963 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[5] ;
  assign y__h29112 = x__h29156 & y__h29157 ;
  assign y__h29157 =
	     x__h29113 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[6] ;
  assign y__h29307 =
	     x__h29263 ^
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d404[7] ;
  assign y__h3256 =
	     IF_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELS_ETC__q1[1] &
	     y__h3301 ;
  assign y__h3301 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[8] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[8] ;
  assign y__h3407 = x__h3451 & y__h3452 ;
  assign y__h3452 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[9] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[9] ;
  assign y__h3557 = x__h3601 & y__h3602 ;
  assign y__h3602 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[10] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[10] ;
  assign y__h36913 = y__h14691 ^ x__h14690 ;
  assign y__h37064 = y__h14843 ^ x__h14842 ;
  assign y__h3707 = x__h3751 & y__h3752 ;
  assign y__h37214 = y__h14995 ^ x__h14994 ;
  assign y__h37364 = y__h15147 ^ x__h15146 ;
  assign y__h37514 = y__h15299 ^ x__h15298 ;
  assign y__h3752 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[11] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[11] ;
  assign y__h37664 = y__h15451 ^ x__h15450 ;
  assign y__h37814 = y__h15603 ^ x__h15602 ;
  assign y__h3857 = x__h3901 & y__h3902 ;
  assign y__h3902 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[12] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[12] ;
  assign y__h4007 = x__h4051 & y__h4052 ;
  assign y__h4052 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[13] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[13] ;
  assign y__h4202 =
	     IF_wr_in_a_whas__5_THEN_wr_in_a_wget__6_ELSE_0___d17[14] ^
	     IF_wr_in_b_whas__9_THEN_wr_in_b_wget__0_ELSE_0___d21[14] ;
  assign y__h45055 =
	     ~_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wget__ETC___d247 ;
  assign y__h45244 = y__h36913 ^ x__h21148 ;
  assign y__h45395 = y__h37064 ^ x__h21298 ;
  assign y__h45545 = y__h37214 ^ x__h21448 ;
  assign y__h45695 = y__h37364 ^ x__h21598 ;
  assign y__h45845 = y__h37514 ^ x__h21748 ;
  assign y__h57081 = x__h57171 | y__h57172 ;
  assign y__h57172 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[1] &
	     mantissa_b__h710[17] ;
  assign y__h57174 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[1] |
	     mantissa_b__h710[17] ;
  assign y__h57353 = x__h57443 | y__h57444 ;
  assign y__h57444 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[2] &
	     mantissa_b__h710[18] ;
  assign y__h57446 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[2] |
	     mantissa_b__h710[18] ;
  assign y__h57624 = x__h57714 | y__h57715 ;
  assign y__h57715 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[3] &
	     mantissa_b__h710[19] ;
  assign y__h57717 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[3] |
	     mantissa_b__h710[19] ;
  assign y__h57895 = x__h57985 | y__h57986 ;
  assign y__h57986 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[4] &
	     mantissa_b__h710[20] ;
  assign y__h57988 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[4] |
	     mantissa_b__h710[20] ;
  assign y__h58166 = x__h58256 | y__h58257 ;
  assign y__h58257 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[5] &
	     mantissa_b__h710[21] ;
  assign y__h58259 =
	     IF_1_CONCAT_IF_wr_in_a_whas__5_THEN_wr_in_a_wg_ETC___d354[5] |
	     mantissa_b__h710[21] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_out_a <= `BSV_ASSIGNMENT_DELAY 16'd0;
	rg_out_b <= `BSV_ASSIGNMENT_DELAY 16'd0;
	rg_out_c <= `BSV_ASSIGNMENT_DELAY 32'd0;
	valid_a_b <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (rg_out_a$EN) rg_out_a <= `BSV_ASSIGNMENT_DELAY rg_out_a$D_IN;
	if (rg_out_b$EN) rg_out_b <= `BSV_ASSIGNMENT_DELAY rg_out_b$D_IN;
	if (rg_out_c$EN) rg_out_c <= `BSV_ASSIGNMENT_DELAY rg_out_c$D_IN;
	if (valid_a_b$EN) valid_a_b <= `BSV_ASSIGNMENT_DELAY valid_a_b$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_out_a = 16'hAAAA;
    rg_out_b = 16'hAAAA;
    rg_out_c = 32'hAAAAAAAA;
    valid_a_b = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putA)
	begin
	  v__h58656 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putA) $display(v__h58656, " [MAC] method reached, putA\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putB)
	begin
	  v__h58740 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putB) $display(v__h58740, " [MAC] method reached, putA\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putS)
	begin
	  v__h58824 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_putS) $display(v__h58824, " [MAC] method reached, putA\n");
  end
  // synopsys translate_on
endmodule  // mk_pe

