SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkPipelined.v


EXTRA_ARGS = --trace --trace-structs

TOPLEVEL_UP = mkUnpipelined
TOPLEVEL = mkPipelined
MODULE_UP  := test_mac
MODULE   := test_mac_p

include $(shell cocotb-config --makefiles)/Makefile.sim
