//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Tue Nov 26 12:57:37 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTB_pipelined(CLK,
		      RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule mac_ifc
  wire [31 : 0] mac_ifc$get_result, mac_ifc$put_c_in;
  wire [15 : 0] mac_ifc$put_a_in, mac_ifc$put_b_in;
  wire mac_ifc$EN_get_result,
       mac_ifc$EN_put,
       mac_ifc$RDY_get_result,
       mac_ifc$RDY_put,
       mac_ifc$put_s1_or_s2_in;

  // submodule mac_ifc
  mkPipelined mac_ifc(.CLK(CLK),
		      .RST_N(RST_N),
		      .put_a_in(mac_ifc$put_a_in),
		      .put_b_in(mac_ifc$put_b_in),
		      .put_c_in(mac_ifc$put_c_in),
		      .put_s1_or_s2_in(mac_ifc$put_s1_or_s2_in),
		      .EN_put(mac_ifc$EN_put),
		      .EN_get_result(mac_ifc$EN_get_result),
		      .RDY_put(mac_ifc$RDY_put),
		      .get_result(mac_ifc$get_result),
		      .RDY_get_result(mac_ifc$RDY_get_result));

  // submodule mac_ifc
  assign mac_ifc$put_a_in = 16'b1100000000000000 ;
  assign mac_ifc$put_b_in = 16'b1100000000000000 ;
  assign mac_ifc$put_c_in = 32'b01000000000000000000000000000000 ;
  assign mac_ifc$put_s1_or_s2_in = 1'b0 ;
  assign mac_ifc$EN_put = mac_ifc$RDY_put ;
  assign mac_ifc$EN_get_result = mac_ifc$RDY_get_result ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE) if (mac_ifc$RDY_get_result) $display("hi");
    if (RST_N != `BSV_RESET_VALUE)
      if (mac_ifc$RDY_get_result) $display("value is %b", mac_ifc$get_result);
    if (RST_N != `BSV_RESET_VALUE) if (mac_ifc$RDY_get_result) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTB_pipelined

